=== TeddyCr/OpenMetadata/openmetadata-spec/src/main/resources/json/schema/api/analytics/createReportDefinition.json
{
    "$id": "https://open-metadata.org/schema/api/tests/createReportDefinition.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "CreateReportDefinition",
    "description": "Payload to create a report definition",
    "type": "object",
    "javaType": "org.openmetadata.schema.api.tests.CreateReportDefinition",
    "javaInterfaces": ["org.openmetadata.schema.CreateEntity"],
    "properties": {
      "name": {
        "description": "Name that identifies this report definition.",
        "$ref": "../../type/basic.json#/definitions/entityName"
      },
      "displayName": {
        "description": "Display Name the report definition.",
        "type": "string"
      },
      "description": {
        "description": "Description of the report definition.",
        "$ref": "../../type/basic.json#/definitions/markdown"
      },
      "reportParametersDefinition": {
        "description": "dimension(s) and metric(s) for a report",
        "$ref": "../../analytics/reportDefinition.json#/definitions/reportParametersDefinition"
      },
      "owner": {
        "description": "Owner of this report definition",
        "$ref": "../../type/entityReference.json"
      }
    },
    "required": ["name", "reportParametersDefinition"],
    "additionalProperties": false
  }

=== TeddyCr/OpenMetadata/openmetadata-service/src/main/resources/json/data/analytics/completedDescriptionByServiceType.json
{
    "name": "completedDescriptionByServiceType",
    "displayName": "Completed Description by Service Type",
    "description": "This report definition shows the number/percentage of completed description by service type (i.e. databases, tables, dashboard, etc.)",
    "reportParametersDefinition": {
        "dimensions": [
            {
                "name": "ServiceType",
                "displayName": "Service Type"
            },
            {
                "name": "Team",
                "displayName": "Team"
            }
        ],
        "metrics": [
            {
                "name": "completed_descriptions",
                "displayName": "Completed Descriptions",
                "dataType": "INT"
            },
            {
                "name": "total_service_types",
                "displayName": "Total Services",
                "dataType": "INT"
            }
        ]
    }
}
